pipeline {
    agent {
        docker { image 'python:latest' }
    }
    stages {
        stage('Build') {
            steps {
                sh 'pip3 install --no-cache-dir -r vote/requirements.txt'
            }
        }
        stage('Test') {
            steps {
                sh 'nosetests -v'
            }
        }
    }
}
