pipeline {
    agent {
        docker { image 'python:latest' }
    }
    stages {
        stage('Build') {
            steps {
                sh 'pip install -i vote/requirements.txt'
            }
        }
        stage('Test') {
            steps {
                sh 'nosetest -v'
            }
        }
    }
}
